### ISSUE TITLE
Usage with nuxt 3 ?

### ISSUE THREAD

**Issue by cfab** [JayeshLab/vue3-resize-text#1]
Wondering how to use this in nuxt 3...
I tried this and some variants but I cannot make it work !
I put the following in a /plugins/resize.js file but I always end up with the error below.
Any help ? 

```js
import VueResizeText from "vue3-resize-text";

export default defineNuxtPlugin((nuxtApp) => {
  console.log("resize plugin", VueResizeText);
  nuxtApp.vueApp.directive("resize-text", {
    mounted(el, binding) {
      VueResizeText(el, binding.value);
    },
    getSSRProps(binding, vnode) {
      // Provide SSR-specific props here if needed
      return {};
    },
  });
});
```

error: 
```
WARN  [Vue warn]: Failed to resolve directive: resize-text


 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'getSSRProps')
  at Module.ssrGetDirectiveProps (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:490:40)  
  at _sfc_ssrRender (./app/components/Hero.vue:72:32)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:710:9)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:654:12)  
  at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)  
  at _sfc_ssrRender (./app/pages/index.vue:123:33)  
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:710:9)  
  at ./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:652:25  
  at async renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:941:18)  
  at Object.renderToString$1 (./node_modules/nuxt/dist/core/runtime/nitro/renderer.js:54:18)
```

**Comment by cfab** [comment]
Of course, as I had adopted the new nuxt 4 files structure if my plugins folder is not in /app, it couldn't work !
But here is a working directive anyway: 
```js
// file plugins/vresize.js
import VueResizeText from "vue3-resize-text";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.directive("ResizeText", VueResizeText.ResizeText);
});
```

**Comment by cfab** [comment]
I close then...
